### ISSUE TITLE
fix: make offline auto-accept snippet also reflect in goal progress bar

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp-snippet-library#101]
## Overview

This snippet works to set the status to complete automatically: https://github.com/impress-org/give-snippet-library/blob/master/gateway-customizations/offline-auto-complete.php

It does NOT reflect in the goal progress bar until the stats are recalculated using the tools at Donations > Tools > Data

## Steps to replicate
1. Create a form with a goal progress bar
1. Install the custom snippet above in a helper plugin, mu-plugin, or the active theme functions.php
1. Enable the offline gateway
1. Submit the donation
1. See that the status is correctly "complete" and the offline instructions are NOT sent.
1. REload a page with the progress bar on it.

## Possible solution
Somehow incorporate `give_update_payment_status()` into that function, to fully simulate the manual process of updating an offline donation to complete.

**Comment by DevinWalker** [comment]
I fixed the snippet - essentially I had to rewrite it using the proper hook to update the status so it reflects properly in the goal. 

See snippet now: https://github.com/impress-org/givewp-snippet-library/blob/master/gateway-customizations/offline-auto-complete.php
