### ISSUE TITLE
Input Tag Not Working

### ISSUE THREAD

**Issue by majidriaz92** [impress-org/givewp-snippet-library#106]
https://github.com/impress-org/givewp-snippet-library/blob/master/form-customizations/custom-fields-plugin.php

This Tag Not Working

`<input type="checkbox" checked name="give_give_donations_export_option[give_engraving_message]" id="give-engraving-message"><?php _e( 'Engraved Message', 'give' ); ?>`

I Got Error

An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.

**Comment by DevinWalker** [comment]
Closing - please open a support request.
