### ISSUE TITLE
Fee Recovery: create code snippet for `give_fee_recovery_message` filter

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp-snippet-library#32]
As issue #54 , we added a filter to fee recovery message HTML markup ( `give_fee_recovery_message`).  Create code snippet to show how we can edit Html markup and save it: https://github.com/WordImpress/Give-Snippet-Library/tree/master/add-on%20snippets/fee-recovery.
**Code**: How to add a tooltip to fee recovery HTML markup, so every can understand it in more depth. 

Note: resolve this issue after fee recovery `1.1.0` will release.

**Comment by DevinWalker** [comment]
Closing - there's been a lack of attention here and support isn't requesting.
